---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1733358/public_html/admins.bspid.id
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R Classes $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH 
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R getphp $DEPLOYPATH
    - /bin/cp -R image $DEPLOYPATH
    - /bin/cp -R library $DEPLOYPATH
    - /bin/cp -R mail $DEPLOYPATH
    - /bin/cp -R pay $DEPLOYPATH
    - /bin/cp -R php $DEPLOYPATH
    - /bin/cp -R uploads $DEPLOYPATH
    - /bin/cp -R view $DEPLOYPATH 
    - /bin/cp .cpanel.yml $DEPLOYPATH    
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp d_print.php $DEPLOYPATH
    - /bin/cp export_mutasi.php $DEPLOYPATH
    - /bin/cp export_trash.php $DEPLOYPATH 
    - /bin/cp export_withdraw.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp loginv2.php $DEPLOYPATH
    - /bin/cp L_BSP_LM_LOGO.png $DEPLOYPATH
    - /bin/cp logout.php $DEPLOYPATH
    - /bin/cp m_print.php $DEPLOYPATH
    - /bin/cp settingdatabase.php $DEPLOYPATH
    - /bin/cp w_print.php $DEPLOYPATH
