---
deployment:
  tasks:
    - export DEPLOYPATH=/home/uruh7792/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp export_mutasi.php $DEPLOYPATH
    - /bin/cp export_trash.php $DEPLOYPATH
    - /bin/cp loginv2.php $DEPLOYPATH
    - /bin/cp logo.jpg $DEPLOYPATH
    - /bin/cp logo.png $DEPLOYPATH
    - /bin/cp mutasicustomerpdf.php $DEPLOYPATH
    - /bin/cp settingdatabase.php $DEPLOYPATH