---
deployment:
  tasks:
    - export DEPLOYPATH=/home/uruh7792/public_html/
    - /bin/cp -R administrator $DEPLOYPATH
    - /bin/cp -R Classes $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R library $DEPLOYPATH
    - /bin/cp -R mail $DEPLOYPATH
    - /bin/cp -R php $DEPLOYPATH
    - /bin/cp -R uploads $DEPLOYPATH
    - /bin/cp -R view $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp export_mutasi.php $DEPLOYPATH
    - /bin/cp export_trash.php $DEPLOYPATH
    - /bin/cp loginv2.php $DEPLOYPATH
    - /bin/cp logo.jpg $DEPLOYPATH
    - /bin/cp logo.png $DEPLOYPATH
    - /bin/cp mutasicustomerpdf.php $DEPLOYPATH
    - /bin/cp settingdatabase.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    