---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1733358/public_html/admins.bspid.id
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH    
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp activasipdf.php $DEPLOYPATH
    - /bin/cp export_mutasi.php $DEPLOYPATH
    - /bin/cp export_trash.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH