---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1733358/public_html/admins.bspid.id
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH    
    - /bin/cp .htaccess $DEPLOYPATH